# This is a basic workflow to help you get started with Actions

name: Publish to GitHub Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Run install
    - name: Install
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        cd ../tiny-prof-viewer
        npm install

    # Run build
    - name: Build
      run: |
        source emsdk/emsdk_env.sh
        cd tiny-prof-viewer
        npm run build -- --base=/tiny-prof --outDir=dist
        npm run build -- --base=/ --outDir=html

    # Deploy
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v4
      with:
        target_branch: pages
        build_dir: tiny-prof-viewer/dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html
        path: |
          tiny-prof-viewer/html
